services:
  warehouse_db:
    container_name: warehouse_db
    image: postgres:16.2
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=warehouse_db
    ports:
      - '5432:5432'
    volumes:
      - ./warehouse_db/:/var/lib/postgresql/data

  warehouse_app:
    build:
      dockerfile: ./Dockerfile
    command:
      - "uvicorn"
      - "main:app"
      - "--host=0.0.0.0"
      - "--port=8000"
    ports:
      - "8000:8000"


